sonar.projectKey=cohort-9-mern-12902-khushi
sonar.projectName=cohort-9-mern-12902-khushi
sonar.sources=frontend/src,backend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.ts,**/*.test.tsx
sonar.host.url=http://localhost:9000
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
